#include"main.h"
/**
*get_size-Calculatesthesizetocasttheargument
*@format:Formattedstringinwhichtoprintthearguments
*@i:Listofargumentstobeprinted.
*
*Return:Precision.
*/
intget_size(constchar*format,int*i)
{
intcurr_i=*i+1;
intsize=0;
if(format[curr_i]=='l')
size=S_LONG;
elseif(format[curr_i]=='h')
size=S_SHORT;
if(size==0)
*i=curr_i-1;
else
*i=curr_i;
return(size);
}

