#include"main.h"
/**
*get_width-Calculatesthewidthforprinting
*@format:Formattedstringinwhichtoprintthearguments.
*@i:Listofargumentstobeprinted.
*@list:listofarguments.
*
*Return:width.
*/
intget_width(constchar*format,int*i,va_listlist)
{
intcurr_i;
intwidth=0;
for(curr_i=*i+1;format[curr_i]!='\0';curr_i++)
{
if(is_digit(format[curr_i]))
{
width*=10;
width+=format[curr_i]-'0';
}
elseif(format[curr_i]=='*')
{
curr_i++;
width=va_arg(list,int);
break;
}
else
break;
}
*i=curr_i-1;
return(width);
}

