#include"main.h"
/**
*get_precision-Calculatestheprecisionforprinting
*@format:Formattedstringinwhichtoprintthearguments
*@i:Listofargumentstobeprinted.
*@list:listofarguments.
*
*Return:Precision.
*/
intget_precision(constchar*format,int*i,va_listlist)
{
intcurr_i=*i+1;
intprecision=-1;
if(format[curr_i]!='.')
return(precision);
precision=0;
for(curr_i+=1;format[curr_i]!='\0';curr_i++)
{
if(is_digit(format[curr_i]))
{
precision*=10;
precision+=format[curr_i]-'0';
}
elseif(format[curr_i]=='*')
{
curr_i++;
precision=va_arg(list,int);
break;
}
else
break;
}
*i=curr_i-1;
return(precision);
}
