#include"main.h"
/**
*handle_print-Printsanargumentbasedonitstype
*@fmt:Formattedstringinwhichtoprintthearguments.
*@list:Listofargumentstobeprinted.
*@ind:ind.
*@buffer:Bufferarraytohandleprint.
*@flags:Calculatesactiveflags
*@width:getwidth.
*@precision:Precisionspecification
*@size:Sizespecifier
*Return:1or2;
*/
inthandle_print(constchar*fmt,int*ind,va_listlist,charbuffer[],
intflags,intwidth,intprecision,intsize)
{
inti,unknow_len=0,printed_chars=-1;
fmt_tfmt_types[]={
{'c',print_char},{'s',print_string},{'%',print_percent},
{'i',print_int},{'d',print_int},{'b',print_binary},
{'u',print_unsigned},{'o',print_octal},{'x',print_hexadecimal},
{'X',print_hexa_upper},{'p',print_pointer},{'S',print_non_printable},
{'r',print_reverse},{'R',print_rot13string},{'\0',NULL}
};
for(i=0;fmt_types[i].fmt!='\0';i++)
if(fmt[*ind]==fmt_types[i].fmt)
return(fmt_types[i].fn(list,buffer,flags,width,precision,size));
if(fmt_types[i].fmt=='\0')
{
if(fmt[*ind]=='\0')
return(-1);
unknow_len+=write(1,"%%",1);
if(fmt[*ind-1]=='')
unknow_len+=write(1,"",1);
elseif(width)
{
--(*ind);
while(fmt[*ind]!=''&&fmt[*ind]!='%')
--(*ind);
if(fmt[*ind]=='')
--(*ind);
return(1);
}
unknow_len+=write(1,&fmt[*ind],1);
return(unknow_len);
}
return(printed_chars);
}
