#include"main.h"
/**
*is_printable-Evaluatesifacharisprintable
*@c:Chartobeevaluated.
*
*Return:1ifcisprintable,0otherwise
*/
intis_printable(charc)
{
if(c>=32&&c<127)
return(1);
return(0);
}
/**
*append_hexa_code-Appendascciinhexadecimalcodetobuffer
*@buffer:Arrayofchars.
*@i:Indexatwhichtostartappending.
*@ascii_code:ASSCICODE.
*Return:Always3
*/
intappend_hexa_code(charascii_code,charbuffer[],inti)
{
charmap_to[]="0123456789ABCDEF";
/*Thehexaformatcodeisalways2digitslong*/
if(ascii_code<0)
ascii_code*=-1;
buffer[i++]='\\';
buffer[i++]='x';
buffer[i++]=map_to[ascii_code/16];
buffer[i]=map_to[ascii_code%16];
return(3);
}
/**
*is_digit-Verifiesifacharisadigit
*@c:Chartobeevaluated
*
*Return:1ifcisadigit,0otherwise
*/
intis_digit(charc)
{
if(c>='0'&&c<='9')
return(1);
return(0);
}
/**
*convert_size_number-Castsanumbertothespecifiedsize
*@num:Numbertobecasted.
*@size:Numberindicatingthetypetobecasted.
*
*Return:Castedvalueofnum
*/
longintconvert_size_number(longintnum,intsize)
{
if(size==S_LONG)
return(num);
elseif(size==S_SHORT)
return((short)num);
return((int)num);
}
/**
*convert_size_unsgnd-Castsanumbertothespecifiedsize
*@num:Numbertobecasted
*@size:Numberindicatingthetypetobecasted
*
*Return:Castedvalueofnum
*/
longintconvert_size_unsgnd(unsignedlongintnum,intsize)
{
if(size==S_LONG)
return(num);
elseif(size==S_SHORT)
return((unsignedshort)num);
return((unsignedint)num);
}

