#include"main.h"
/*************************WRITEHANDLE*************************/
/**
*handle_write_char-Printsastring
*@c:chartypes.
*@buffer:Bufferarraytohandleprint
*@flags:Calculatesactiveflags.
*@width:getwidth.
*@precision:precisionspecifier
*@size:Sizespecifier
*
*Return:Numberofcharsprinted.
*/
inthandle_write_char(charc,charbuffer[],
intflags,intwidth,intprecision,intsize)
{/*charisstoredatleftandpaddindatbuffer'sright*/
inti=0;
charpadd='';
UNUSED(precision);
UNUSED(size);
if(flags&F_ZERO)
padd='0';
buffer[i++]=c;
buffer[i]='\0';
if(width>1)
{
buffer[BUFF_SIZE-1]='\0';
for(i=0;i<width-1;i++)
buffer[BUFF_SIZE-i-2]=padd;
if(flags&F_MINUS)
return(write(1,&buffer[0],1)+
write(1,&buffer[BUFF_SIZE-i-1],width-1));
else
return(write(1,&buffer[BUFF_SIZE-i-1],width-1)+
write(1,&buffer[0],1));
}
return(write(1,&buffer[0],1));
}
/*************************WRITENUMBER*************************/
/**
*write_number-Printsastring
*@is_negative:Listaofarguments
*@ind:chartypes.
*@buffer:Bufferarraytohandleprint
*@flags:Calculatesactiveflags
*@width:getwidth.
*@precision:precisionspecifier
*@size:Sizespecifier
*
*Return:Numberofcharsprinted.
*/
intwrite_number(intis_negative,intind,charbuffer[],
intflags,intwidth,intprecision,intsize)
{
intlength=BUFF_SIZE-ind-1;
charpadd='',extra_ch=0;
UNUSED(size);
if((flags&F_ZERO)&&!(flags&F_MINUS))
padd='0';
if(is_negative)
extra_ch='-';
elseif(flags&F_PLUS)
extra_ch='+';
elseif(flags&F_SPACE)
extra_ch='';
return(write_num(ind,buffer,flags,width,precision,
length,padd,extra_ch));
}
/**
*write_num-Writeanumberusingabufffer
*@ind:Indexatwhichthenumberstartsonthebuffer
*@buffer:Buffer
*@flags:Flags
*@width:width
*@prec:Precisionspecifier
*@length:Numberlength
*@padd:Padingchar
*@extra_c:Extrachar
*
*Return:Numberofprintedchars.
*/
intwrite_num(intind,charbuffer[],
intflags,intwidth,intprec,
intlength,charpadd,charextra_c)
{
inti,padd_start=1;
if(prec==0&&ind==BUFF_SIZE-2&&buffer[ind]=='0'&&width==0)
return(0);/*printf(".0d",0)nocharisprinted*/
if(prec==0&&ind==BUFF_SIZE-2&&buffer[ind]=='0')
buffer[ind]=padd='';/*widthisdisplayedwithpadding''*/
if(prec>0&&prec<length)
padd='';
while(prec>length)
buffer[--ind]='0',length++;
if(extra_c!=0)
length++;
if(width>length)
{
for(i=1;i<width-length+1;i++)
buffer[i]=padd;
buffer[i]='\0';
if(flags&F_MINUS&&padd=='')/*Asignextrachartoleftofbuffer*/
{
if(extra_c)
buffer[--ind]=extra_c;
return(write(1,&buffer[ind],length)+write(1,&buffer[1],i-1));
}
elseif(!(flags&F_MINUS)&&padd=='')/*extrachartoleftofbuff*/
{
if(extra_c)
buffer[--ind]=extra_c;
return(write(1,&buffer[1],i-1)+write(1,&buffer[ind],length));
}
elseif(!(flags&F_MINUS)&&padd=='0')/*extrachartoleftofpadd*/
{
if(extra_c)
buffer[--padd_start]=extra_c;
return(write(1,&buffer[padd_start],i-padd_start)+
write(1,&buffer[ind],length-(1-padd_start)));
}
}
if(extra_c)
buffer[--ind]=extra_c;
return(write(1,&buffer[ind],length));
}
/**
*write_unsgnd-Writesanunsignednumber
*@is_negative:Numberindicatingifthenumisnegative
*@ind:Indexatwhichthenumberstartsinthebuffer
*@buffer:Arrayofchars
*@flags:Flagsspecifiers
*@width:Widthspecifier
*@precision:Precisionspecifier
*@size:Sizespecifier
*
*Return:Numberofwrittenchars.
*/
intwrite_unsgnd(intis_negative,intind,
charbuffer[],
intflags,intwidth,intprecision,intsize)
{
/*Thenumberisstoredatthebufer'srightandstartsatpositioni*/
intlength=BUFF_SIZE-ind-1,i=0;
charpadd='';
UNUSED(is_negative);
UNUSED(size);
if(precision==0&&ind==BUFF_SIZE-2&&buffer[ind]=='0')
return(0);/*printf(".0d",0)nocharisprinted*/
if(precision>0&&precision<length)
padd='';
while(precision>length)
{
buffer[--ind]='0';
length++;
}
if((flags&F_ZERO)&&!(flags&F_MINUS))
padd='0';
if(width>length)
{
for(i=0;i<width-length;i++)
buffer[i]=padd;
buffer[i]='\0';
if(flags&F_MINUS)/*Asignextrachartoleftofbuffer[buffer>padd]*/
{
return(write(1,&buffer[ind],length)+write(1,&buffer[0],i));
}
else/*Asignextrachartoleftofpadding[padd>buffer]*/
{
return(write(1,&buffer[0],i)+write(1,&buffer[ind],length));
}
}
return(write(1,&buffer[ind],length));
}
/**
*write_pointer-Writeamemoryaddress
*@buffer:Arraysofchars
*@ind:Indexatwhichthenumberstartsinthebuffer
*@length:Lengthofnumber
*@width:Widthspecifier
*@flags:Flagsspecifier
*@padd:Charrepresentingthepadding
*@extra_c:Charrepresentingextrachar
*@padd_start:Indexatwhichpaddingshouldstart
*
*Return:Numberofwrittenchars.
*/
intwrite_pointer(charbuffer[],intind,intlength,
intwidth,intflags,charpadd,charextra_c,intpadd_start)
{
inti;
if(width>length)
{
for(i=3;i<width-length+3;i++)
buffer[i]=padd;
buffer[i]='\0';
if(flags&F_MINUS&&padd=='')/*Asignextrachartoleftofbuffer*/
{
buffer[--ind]='x';
buffer[--ind]='0';
if(extra_c)
buffer[--ind]=extra_c;
return(write(1,&buffer[ind],length)+write(1,&buffer[3],i-3));
}
elseif(!(flags&F_MINUS)&&padd=='')/*extrachartoleftofbuffer*/
{
buffer[--ind]='x';
buffer[--ind]='0';
if(extra_c)
buffer[--ind]=extra_c;
return(write(1,&buffer[3],i-3)+write(1,&buffer[ind],length));
}
elseif(!(flags&F_MINUS)&&padd=='0')/*extrachartoleftofpadd*/
{
if(extra_c)
buffer[--padd_start]=extra_c;
buffer[1]='0';
buffer[2]='x';
return(write(1,&buffer[padd_start],i-padd_start)+
write(1,&buffer[ind],length-(1-padd_start)-2));
}
}
buffer[--ind]='x';
buffer[--ind]='0';
if(extra_c)
buffer[--ind]=extra_c;
return(write(1,&buffer[ind],BUFF_SIZE-ind-1));
}
